default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: root@123
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pet_haven_hub_development

test:
  <<: *default
  database: pet_haven_hub_test
