default: &default
  adapter: postgresql
  encoding: unicode
  username: bharat
  password: root123
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pet_haven_hub_development

test:
  <<: *default
  database: pet_haven_hub_test
